#### Tensor 이해

In [6]:
# 모듈 로딩
import torch

- Tensor 생성 [2] torch.rand()

In [8]:
# 0<= ~ <1 범위의 임의의 숫자 1개 추출 => rand(*size)
# rand(*size) : 가변인자 => 몇 차원일지 알 수 없음!
torch.manual_seed(1)

dataTS1=torch.rand(3) # 1D vector
dataTS2=torch.rand(2,3) # 2D Matrix
dataTS3=torch.rand(2,1,3) # 3D Tensor

In [5]:
print(dataTS1, dataTS2, dataTS3, sep='\n')

tensor([0.7576, 0.2793, 0.4031])
tensor([[0.7347, 0.0293, 0.7999],
        [0.3971, 0.7544, 0.5695]])
tensor([[[0.4388, 0.6387, 0.5247]],

        [[0.6826, 0.3051, 0.4635]]])


- Tensor생성 [3] torch.randn()

In [10]:
dataTS1=torch.randn(3) # 1D Vector
dataTS2=torch.randn(2,3) # 2D Matrix
dataTS3=torch.randn(2,1,3) # 3D Tensor

print(dataTS1, dataTS2, dataTS3, sep='\n')

tensor([-1.8349, -2.2149,  0.0436])
tensor([[ 1.3240, -0.1005,  0.6443],
        [ 0.5244,  1.0157,  0.2571]])
tensor([[[-0.9013,  0.8138,  0.3871]],

        [[ 0.5417,  0.6646,  0.3248]]])


- Tensor 생성 [4] torch.randint()

In [12]:
# 1D Vector
torch.randint(1,46,(6,))

tensor([40, 24,  4,  4, 17, 33])

In [13]:
# 2D Matrix
torch.randint(1,46,(4,6))

tensor([[38, 44,  5, 39, 21, 18],
        [ 8,  4, 21, 40, 45, 26],
        [22, 28, 18,  1, 11, 16],
        [35, 32, 17, 25,  6, 14]])