### TENSOR 변환
- torch.as_tensor() 
    * 동일 타입과 디바이스를 가진 데이터 존재 ==> view 즉, 데이터 공유
    * 다른 타입 또는 다른 디바이스를 가진 데이터 존재 ==> copy 즉, 생성
    * view tensor 또는 copy tensor 반환
    

In [1]:
## 모듈 로딩
import torch               

- Python 객체 ==> Tensor 변환 

In [2]:
## List ==> Tensor
data = list(range(1, 10))

In [3]:
## torch.as_tensor() 
dataTS=torch.as_tensor(data, dtype=torch.int8)
dataTS, dataTS.shape, dataTS.ndim, dataTS.dtype

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8),
 torch.Size([9]),
 1,
 torch.int8)

In [4]:
data[0]=100

In [5]:
data, dataTS

([100, 2, 3, 4, 5, 6, 7, 8, 9],
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8))

- Numpy ndarray 객체 ==> Tensor 변환

In [6]:
import numpy as np                   

In [7]:
dataTS=torch.tensor([1,2,3])
dataTS, dataTS.shape, dataTS.ndim

(tensor([1, 2, 3]), torch.Size([3]), 1)

In [8]:
arr1=np.array([1,2,3])
arr1, arr1.dtype, arr1.ndim

(array([1, 2, 3]), dtype('int32'), 1)

In [9]:
arrTS=torch.as_tensor(arr1, dtype=torch.float32)
arrTS

tensor([1., 2., 3.])

In [10]:
arr1[0]=77

In [11]:
arr1, arrTS

(array([77,  2,  3]), tensor([1., 2., 3.]))

In [12]:
arrTS[0]=99

In [13]:
arr1, arrTS

(array([77,  2,  3]), tensor([99.,  2.,  3.]))

- Numpy ndarray ==> Tensor 변환 : from_numpy()

In [25]:
arr1=np.array([ [5,7,9],[1,2,3] ], dtype=np.float16)
print(arr1)
print(f'데이터 저장 메모리  : {arr1.data}')
print(f'원소/요소 개수      : {arr1.size}')
print(f'원소/요소 1개 크기  : {arr1.itemsize}')
print(f'타입               : {arr1.dtype}')
print(f'방향               : {arr1.strides}')

[[5. 7. 9.]
 [1. 2. 3.]]
데이터 저장 메모리  : <memory at 0x000001F059C59A00>
원소/요소 개수      : 6
원소/요소 1개 크기  : 2
타입               : float16
방향               : (6, 2)


In [26]:
arrTS=torch.from_numpy(arr1)
arrTS

tensor([[5., 7., 9.],
        [1., 2., 3.]], dtype=torch.float16)

In [28]:
np.float32 , torch.float

(numpy.float32, torch.float32)