#### Tensor의 모양/형태/shape 변경과 View Tensor

In [22]:
# 모듈 로딩
import numpy as np
import torch

In [23]:
# Tensor 생성
dataTS=torch.arange(1,21)
print(dataTS, dataTS.ndim, dataTS.stride(), sep='\n')

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])
1
(1,)


In [24]:
# 1D => 2D 형태/모양/Shape 변경
dataTS2=dataTS.reshape((-1,5))
print(dataTS2, dataTS2.ndim, dataTS2.stride(), sep='\n')
print(f'is_contiguous() : {dataTS2.is_contiguous()}')

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])
2
(5, 1)
is_contiguous() : True


In [25]:
print(dataTS2.storage())

 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]


In [26]:
dataTS22=dataTS2.reshape((-1,2))
print(dataTS22, dataTS22.ndim, dataTS22.stride(), sep='\n')
print(f'is_contiguous() : {dataTS2.is_contiguous()}')

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]])
2
(2, 1)
is_contiguous() : True


In [30]:
dataTS23=dataTS22.T # 전치
dataTS23.is_contiguous()

False

In [32]:
# 불연속적 => 연속적으로 저징되도록 
dTS=dataTS23.contiguous()

In [34]:
dTS.is_contiguous()

True